from flask import Flask, render_template, request
from google import genai
from career_data import career_data, kcet_colleges, percentage_courses, scholarships,roadmaps
from flask import send_file
from reportlab.pdfgen import canvas
import io

app = Flask(__name__)
app.secret_key = "ai_career_guide_secret_2026"
app.config["THEME"] = "blue-black"

client = genai.Client(api_key="YOUR_GEMINI_API_KEY")

@app.route("/", methods=["GET", "POST"])
def home():
    recommendations = []
    college_recommendations = []
    roadmap = []
    scholarship_list = []
    bot_reply = ""
    user_message = ""
    student_name = ""
    percentage = None
    stream = ""
    rank = ""
    education = ""
    value = None

    if request.method == "POST":
        student_name = request.form.get("name")
        stream = request.form.get("stream")
        rank = request.form.get("rank")
        education = request.form.get("education")
        user_message = request.form.get("message")
        career_goal = request.form.get("career_goal")

        recommendations = career_data.get(stream, [])
        if career_goal:
            roadmap = roadmaps.get(career_goal, [])

        # Gemini AI Chatbot
        if user_message:
            try:
                response = client.models.generate_content(
                    model="gemini-3.5-flash",
                    contents=user_message
                )
                bot_reply = response.text
            except Exception as e:
                bot_reply = f"AI Error: {e}"

        # Scholarships
        if education:
            scholarship_list = scholarships.get(education, [])

        if rank:
            value = int(rank)

            # Percentage Logic
            if value <= 100:
                percentage = value

                if value >= 90:
                    recommendations = percentage_courses["90-100"]
                elif value >= 80:
                    recommendations = percentage_courses["80-89"]
                elif value >= 70:
                    recommendations = percentage_courses["70-79"]
                elif value >= 50:
                    recommendations = percentage_courses["50-69"]

            # KCET Rank Logic
            else:
                if value <= 1000:
                    college_recommendations = kcet_colleges["1-1000"]
                elif value <= 5000:
                    college_recommendations = kcet_colleges["1001-5000"]
                elif value <= 10000:
                    college_recommendations = kcet_colleges["5001-10000"]
                else:
                    college_recommendations = kcet_colleges["10001-300000"]

    return render_template(
        "index.html",
        recommendations=recommendations,
        roadmap=roadmap,
        student_name=student_name,
        colleges=college_recommendations,
        percentage=percentage,
        scholarships=scholarship_list,
        bot_reply=bot_reply,
        user_message=user_message
    )

@app.route("/resume", methods=["GET", "POST"])
def resume():

    if request.method == "POST":

        fullname = request.form.get("fullname")
        email = request.form.get("email")
        phone = request.form.get("phone")
        education = request.form.get("education")
        skills = request.form.get("skills")
        projects = request.form.get("projects")
        
        return render_template(
            "resume.html",
            fullname=fullname,
            email=email,
            phone=phone,
            education=education,
            skills=skills,
            projects=projects
        )

    return render_template("resume.html")
@app.route("/download_resume", methods=["POST"])
def download_resume():

    fullname = request.form.get("fullname")
    email = request.form.get("email")
    phone = request.form.get("phone")
    education = request.form.get("education")
    skills = request.form.get("skills")
    projects = request.form.get("projects")

    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer)

    pdf.setTitle("Resume")

    pdf.setFont("Helvetica-Bold",24)
    pdf.drawCentredString(300,810,"Professional Resume")

    pdf.setFont("Helvetica",11)
    pdf.drawCentredString(300,792,"Generated by AI Career Guide")

    pdf.line(50,780,550,780)

    pdf.setFont("Helvetica",12)

    y = 760

    pdf.drawString(50, y, f"Name: {fullname}")
    y -= 25

    pdf.drawString(50, y, f"Email: {email}")
    y -= 25

    pdf.drawString(50, y, f"Phone: {phone}")
    y -= 35

    pdf.setFont("Helvetica-Bold",14)
    pdf.drawString(50, y, "Education")
    y -= 20

    pdf.setFont("Helvetica",12)
    pdf.drawString(50, y, education)
    y -= 35

    pdf.setFont("Helvetica-Bold",14)
    pdf.drawString(50, y, "Skills")
    y -= 20

    pdf.setFont("Helvetica",12)
    pdf.drawString(50, y, skills)
    y -= 35

    pdf.setFont("Helvetica-Bold",14)
    pdf.drawString(50, y, "Projects")
    y -= 20

    pdf.setFont("Helvetica",12)
    pdf.drawString(50, y, projects)

    pdf.save()

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name="Resume.pdf",
        mimetype="application/pdf"
    )

if __name__ == "__main__":
    app.run(debug=True)